Fix legacy 1.7 build [with potential downsides]
NixOS/nixops pull request #1401
Opened 2020-09-12 15:47 UTC by allgreed

There was some incompatibilities that prevented the build from
completing, I've patched them to make it work, commenting out a few
lines of code (marked in README) - this is likely break GCE and Azure
potentially, but I haven't tested. Works on existing (pre 2.0) nixops
project out of the box (with DigitalOcean as the cloud of choice).

But I guess that partially working legacy nixops is better than one that cannot be built

2020-09-12 17:40 UTC, cole-h requested changes

2020-09-12 17:40 UTC, cole-h commented on nix/azure.nix
> +    #  type = with types; loaOf (submodule fileSystemsOptions);
`loaOf` is an alias to `attrsOf` now, so why not just change the type to `attrsOf` proper and be done with it? Doesn't seem necessary to comment it out and break things.

2020-09-12 17:40 UTC, cole-h commented on nix/gce.nix
> +    #  type = with types; loaOf (submodule fileSystemsOptions);
Same.

2020-09-12 20:01 UTC, allgreed commented
@cole-h I've changed the `loaOf` as per your suggestion (in the whole project), however then the entire thing breaks:
```
error: The option `fileSystems.<name>.device' defined in `[ path to repo ]/nixops/nix/gce.nix' does not exist.
```

also: any idea what to put instead of `type = types.listOf types.string;`? This one seems to be deprecated as well

2020-09-12 20:08 UTC, mystfox commented
There's not a one-size-fits all replacement, https://github.com/NixOS/nixpkgs/pull/66346 has a summary of the options.

2020-09-13 15:00 UTC, allgreed commented
@mystfox thanks for the suggestions, all done [and Travis is now passing <3]. Previously I was just trying to see if it will work ;)

Unfortunately I have no idea how to fix the `fileSystems` issue with azure and gce

2021-07-07 11:31 UTC, adisbladis commented
Closing this as it's very likely stale and 1.7 is not seeing any development.

Feel free to reopen if it's still relevant.

2021-07-07 11:31 UTC, closed without merging