Add a disclaimer to the README
NixOS/nixops pull request #1576
Opened 2024-03-05 06:29 UTC by thufschmitt

Warn about the low maintenance mode of the project, and tell people about the new NixOps4

cc @roberth . How does that look to you?

2024-03-08 08:56 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/tweag-nix-dev-update-55/40996/1

2024-03-08 13:02 UTC, asymmetric requested changes

2024-03-08 13:02 UTC, asymmetric commented on README.md
> +> An experimental rewrite of NixOps is happening under https://github.com/NixOps4/nixops
404

2024-04-01 15:45 UTC, Ericson2314 commented on README.md
> +> An experimental rewrite of NixOps is happening under https://github.com/NixOps4/nixops
```suggestion
> An experimental rewrite of NixOps is happening under https://github.com/nixops4/nixops4
```
I guess it's case sensative

2024-04-01 15:48 UTC, roberth approved these changes

2024-04-03 07:06 UTC, thufschmitt commented
@roberth : can you merge? I don't have the right to

2024-04-10 11:14 UTC, merged